import '@/styles/globals.scss';

import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import { Footer } from '@/components/layout/Footer/Footer';

const outfitSans = Outfit({
  variable: '--font-outfit',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${outfitSans.variable} `}>
        <main>{children} </main>
        <Footer />
      </body>
    </html>
  );
}
